// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyea3O2-Q_AQ8kR_RnLbqVHT99u1T8wVQ',
    appId: '1:417250253546:web:0dc387c567e1b27f395593',
    messagingSenderId: '417250253546',
    projectId: 'my-notebook-5abfa',
    authDomain: 'my-notebook-5abfa.firebaseapp.com',
    storageBucket: 'my-notebook-5abfa.firebasestorage.app',
    measurementId: 'G-1S9FQCRP8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4lH5kMjgG__5txpYzFtL68hx9JaDQeB8',
    appId: '1:417250253546:android:81ace5349551b06a395593',
    messagingSenderId: '417250253546',
    projectId: 'my-notebook-5abfa',
    storageBucket: 'my-notebook-5abfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kC_9LLBr4V8WNKEpw--K9GQVo90hFxQ',
    appId: '1:417250253546:ios:9dfe6e196737c23a395593',
    messagingSenderId: '417250253546',
    projectId: 'my-notebook-5abfa',
    storageBucket: 'my-notebook-5abfa.firebasestorage.app',
    iosClientId: '417250253546-ihpe2lenh18b27m95cvcjq4n331cjfb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kC_9LLBr4V8WNKEpw--K9GQVo90hFxQ',
    appId: '1:417250253546:ios:9dfe6e196737c23a395593',
    messagingSenderId: '417250253546',
    projectId: 'my-notebook-5abfa',
    storageBucket: 'my-notebook-5abfa.firebasestorage.app',
    iosClientId: '417250253546-ihpe2lenh18b27m95cvcjq4n331cjfb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyea3O2-Q_AQ8kR_RnLbqVHT99u1T8wVQ',
    appId: '1:417250253546:web:e7e068453f42ba45395593',
    messagingSenderId: '417250253546',
    projectId: 'my-notebook-5abfa',
    authDomain: 'my-notebook-5abfa.firebaseapp.com',
    storageBucket: 'my-notebook-5abfa.firebasestorage.app',
    measurementId: 'G-KMHX3LR83Y',
  );

}